import { AsyncLocalStorage } from 'node:async_hooks'
import { Pool, type PoolClient, type QueryResultRow } from 'pg'
import bcrypt from 'bcryptjs'

const connectionString = process.env.DATABASE_URL
if (!connectionString) throw new Error('DATABASE_URL wajib diisi untuk koneksi Supabase Postgres.')

const pool = new Pool({ connectionString, ssl: { rejectUnauthorized: false }, max: 5 })
const transactionStore = new AsyncLocalStorage<PoolClient>()

const placeholders = (sql: string) => {
  let index = 0
  return sql.replace(/\?/g, () => `$${++index}`)
}

type Statement = {
  get: (...params: unknown[]) => Promise<QueryResultRow | undefined>
  all: (...params: unknown[]) => Promise<QueryResultRow[]>
  run: (...params: unknown[]) => Promise<{ changes: number; lastInsertRowid: number | undefined }>
}

const prepare = (sql: string): Statement => ({
  async get(...params) { return (await query(sql, params)).rows[0] },
  async all(...params) { return (await query(sql, params)).rows },
  async run(...params) {
    const result = await query(sql, params)
    return { changes: result.rowCount || 0, lastInsertRowid: result.rows[0]?.id as number | undefined }
  },
})

async function query(sql: string, params: unknown[] = []) {
  const client = transactionStore.getStore()
  return client ? client.query(placeholders(sql), params) : pool.query(placeholders(sql), params)
}

export const db = {
  prepare,
  async transaction<T>(callback: () => Promise<T>) {
    const client = await pool.connect()
    try {
      await client.query('BEGIN')
      const result = await transactionStore.run(client, callback)
      await client.query('COMMIT')
      return result
    } catch (error) {
      await client.query('ROLLBACK')
      throw error
    } finally { client.release() }
  },
}

export async function migrate() {
  await query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      display_name TEXT NOT NULL,
      role TEXT NOT NULL CHECK(role IN ('admin', 'kasir')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      sku TEXT NOT NULL UNIQUE,
      category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
      price INTEGER NOT NULL CHECK(price >= 0), stock INTEGER NOT NULL DEFAULT 0 CHECK(stock >= 0),
      image_url TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', visits INTEGER NOT NULL DEFAULT 0,
      total_spend INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      transaction_number TEXT NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      cashier_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL, customer_name TEXT NOT NULL,
      subtotal INTEGER NOT NULL CHECK(subtotal >= 0), discount INTEGER NOT NULL DEFAULT 0 CHECK(discount >= 0),
      tax INTEGER NOT NULL DEFAULT 0 CHECK(tax >= 0), total INTEGER NOT NULL CHECK(total >= 0),
      payment_method TEXT NOT NULL CHECK(payment_method IN ('Tunai', 'QRIS', 'Debit / Kredit', 'E-Wallet')),
      cash_received INTEGER NOT NULL DEFAULT 0, change_amount INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'completed', cancel_reason TEXT, cancelled_at TIMESTAMPTZ,
      cancelled_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
      payment_status TEXT NOT NULL DEFAULT 'settlement', gateway_order_id TEXT UNIQUE,
      gateway_token TEXT, gateway_payload TEXT
    );
    CREATE TABLE IF NOT EXISTS transaction_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
      product_id INTEGER REFERENCES products(id) ON DELETE SET NULL, product_name TEXT NOT NULL,
      product_sku TEXT NOT NULL, unit_price INTEGER NOT NULL CHECK(unit_price >= 0),
      quantity INTEGER NOT NULL CHECK(quantity > 0), line_total INTEGER NOT NULL CHECK(line_total >= 0)
    );
    CREATE TABLE IF NOT EXISTS shifts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cashier_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, closed_at TIMESTAMPTZ,
      opening_cash INTEGER NOT NULL DEFAULT 0, closing_cash INTEGER, expected_cash INTEGER, notes TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
    CREATE INDEX IF NOT EXISTS idx_transactions_cashier ON transactions(cashier_id, created_at);
    CREATE INDEX IF NOT EXISTS idx_transaction_items_transaction ON transaction_items(transaction_id);
    CREATE INDEX IF NOT EXISTS idx_shifts_cashier ON shifts(cashier_id, opened_at);
  `)
}

export async function seedDatabase() {
  const count = await db.prepare('SELECT COUNT(*) AS count FROM users').get() as { count: string }
  if (Number(count.count) === 0) {
    const adminPassword = process.env.SEED_ADMIN_PASSWORD
    const cashierPassword = process.env.SEED_CASHIER_PASSWORD
    if (!adminPassword || !cashierPassword) throw new Error('Database kosong. Isi SEED_ADMIN_PASSWORD dan SEED_CASHIER_PASSWORD di environment variables.')
    await db.prepare('INSERT INTO users(username, password_hash, display_name, role) VALUES (?, ?, ?, ?)').run(process.env.SEED_ADMIN_USERNAME || 'owner', bcrypt.hashSync(adminPassword, 12), process.env.SEED_ADMIN_NAME || 'Pemilik Toko', 'admin')
    await db.prepare('INSERT INTO users(username, password_hash, display_name, role) VALUES (?, ?, ?, ?)').run(process.env.SEED_CASHIER_USERNAME || 'kasir', bcrypt.hashSync(cashierPassword, 12), process.env.SEED_CASHIER_NAME || 'Kasir Utama', 'kasir')
  }
  await db.prepare('INSERT INTO settings(key, value) VALUES (?, ?) ON CONFLICT(key) DO NOTHING').run('storeName', process.env.STORE_NAME || 'KasirKita')
  await db.prepare('INSERT INTO settings(key, value) VALUES (?, ?) ON CONFLICT(key) DO NOTHING').run('taxRate', process.env.DEFAULT_TAX_RATE || '11')
  const categoryCount = await db.prepare('SELECT COUNT(*) AS count FROM categories').get() as { count: string }
  if (Number(categoryCount.count) === 0) for (const name of ['Makanan', 'Minuman', 'Camilan']) await db.prepare('INSERT INTO categories(name) VALUES (?)').run(name)
}
