import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import { api, ApiError } from './api'
import * as XLSX from 'xlsx'
import { jsPDF } from 'jspdf'
import './styles.css'

type SnapCallbacks={onSuccess?:()=>void;onPending?:()=>void;onError?:()=>void;onClose?:()=>void}
type SnapApi={pay:(token:string,callbacks:SnapCallbacks)=>void}
declare global { interface Window { snap?:SnapApi } }

type IconName = 'grid'|'bag'|'tag'|'receipt'|'chart'|'users'|'settings'|'search'|'bell'|'chevron'|'plus'|'minus'|'trash'|'arrow'|'dots'|'menu'|'close'|'filter'|'calendar'|'edit'|'wallet'|'cash'|'printer'|'check'|'box'|'userplus'|'logout'|'ban'|'refresh'|'percent'|'shift'
const icons: Record<IconName, ReactNode> = {
 grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>, bag:<><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>, tag:<><path d="M20.6 13.4 13.4 20.6a2 2 0 0 1-2.8 0L3.4 13.4a2 2 0 0 1 0-2.8l7.2-7.2a2 2 0 0 1 2.8 0l7.2 7.2a2 2 0 0 1 0 2.8Z"/><circle cx="9" cy="9" r="1"/></>, receipt:<><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6M9 16h4"/></>, chart:<><path d="M4 19V5M4 19h17"/><path d="m7 15 4-4 3 2 5-6"/></>, users:<><path d="M16 20v-1.5a4.5 4.5 0 0 0-4.5-4.5h-4A4.5 4.5 0 0 0 3 18.5V20"/><circle cx="9.5" cy="7" r="4"/><path d="M17 4.5a4 4 0 0 1 0 7M21 20v-1.5a4.5 4.5 0 0 0-3-4.24"/></>, settings:<><circle cx="12" cy="12" r="3"/><path d="M4 12h3M17 12h3M12 4v3M12 17v3"/></>, search:<><circle cx="11" cy="11" r="6"/><path d="m20 20-4.2-4.2"/></>, bell:<><path d="M18 9a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, chevron:<path d="m9 18 6-6-6-6"/>, plus:<path d="M12 5v14M5 12h14"/>, minus:<path d="M5 12h14"/>, trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></>, arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>, dots:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>, menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>, close:<path d="m6 6 12 12M18 6 6 18"/>, filter:<><path d="M4 5h16M7 12h10M10 19h4"/></>, calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>, edit:<><path d="m14 5 5 5M4 20l4.5-1 10.8-10.8a2.1 2.1 0 0 0-3-3L5.5 16 4 20Z"/></>, wallet:<><path d="M4 7a3 3 0 0 1 3-3h11v16H7a3 3 0 0 1-3-3V7Z"/><path d="M18 9h2v6h-2a3 3 0 0 1 0-6Z"/></>, cash:<><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/></>, printer:<><path d="M6 9V3h12v6M6 18H4V10h16v8h-2M6 15h12v6H6v-6Z"/></>, check:<path d="m5 12 4.5 4.5L19 7"/>, box:<><path d="m3 7 9-4 9 4-9 4-9-4Z"/><path d="M3 7v10l9 4 9-4V7M12 11v10"/></>, userplus:<><path d="M15 20v-1.5A4.5 4.5 0 0 0 10.5 14h-3A4.5 4.5 0 0 0 3 18.5V20"/><circle cx="9" cy="7" r="4"/><path d="M19 8v6M16 11h6"/></>, logout:<><path d="M10 17l5-5-5-5M15 12H3"/><path d="M13 4h5a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-5"/></>,
 ban:<><circle cx="12" cy="12" r="9"/><path d="m5.5 5.5 13 13"/></>,
 refresh:<path d="M4 12a8 8 0 0 1 14.93-4H15m5 0V4M4 12a8 8 0 0 0 14.93 4H15m5 0v4"/>,
 percent:<><path d="M19 5 5 19"/><circle cx="6.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/></>,
 shift:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M8 12h8M12 8v8"/></>,
}
function Icon({ name, size = 20 }: { name: IconName; size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{icons[name]}</svg> }
type Role = 'admin'|'kasir'
type User={id:number;username:string;displayName:string;role:Role}
type Product={id:number;name:string;sku:string;category:string;price:number;stock:number;image:string}
type Category={id:number;name:string;productCount:number}
type Item={id:number;name:string;sku?:string;price:number;quantity:number;lineTotal?:number}
type Payment='Tunai'|'QRIS'|'Debit / Kredit'|'E-Wallet'
type TransactionStatus='completed'|'pending'|'cancelled'
type Transaction={id:string;databaseId?:number;date:string;cashier:string;customer:string;items:Item[];subtotal:number;discount:number;tax:number;total:number;payment:Payment;cashReceived:number;change:number;status?:TransactionStatus;paymentStatus?:string;snapToken?:string|null;clientKey?:string|null;cancelReason?:string|null;cancelledAt?:string|null}
type Customer={id:number;name:string;phone:string;visits:number;spend:number}
type Settings={storeName:string;taxRate:number}
type DashboardData={sales:number;transactions:number;stock:number;customers:number}
type Report={totals:{transactions:number;revenue:number};topProducts:{name:string;quantity:number}[];trend:{date:string;transactions:number;revenue:number}[];cashiers:{id:number;name:string}[];selectedCashierId:number|null;from:string|null;to:string|null;lowStock:Product[]}
type OfflineCheckout={id:string;payload:{items:{id:number;quantity:number}[];discount:number;payment:Payment;cashReceived:number;customerName:string};createdAt:string}
type Shift={id:number;openedAt:string;openingCash:number}
type DiscountType='nominal'|'persen'
type StockFilter='semua'|'tersedia'|'rendah'|'habis'
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const dateText=(d:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d))
const todayISO=()=>new Date().toISOString().slice(0,10)
const exportTransactionsXlsx=(transactions:Transaction[])=>{const rows=transactions.map(t=>({Nomor:t.id,Tanggal:dateText(t.date),Kasir:t.cashier,Pelanggan:t.customer,Metode:t.payment,Status:t.status==='cancelled'?'Dibatalkan':t.status==='pending'?'Menunggu':'Selesai',Total:t.total}));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),'Transaksi');XLSX.writeFile(book,'riwayat-transaksi.xlsx')}
const exportTransactionsPdf=(transactions:Transaction[])=>{const pdf=new jsPDF({unit:'mm',format:'a4'});pdf.setFontSize(16);pdf.text('Riwayat Transaksi',14,16);pdf.setFontSize(9);transactions.forEach((t,index)=>{const y=25+index*8;if(y>285){pdf.addPage();}pdf.text(`${t.id} | ${dateText(t.date)} | ${t.cashier} | ${t.status==='cancelled'?'Dibatalkan':t.status==='pending'?'Menunggu':'Selesai'} | ${money(t.total)}`,14,y>285?15:y) });pdf.save('riwayat-transaksi.pdf')}
const exportReportXlsx=(report:Report)=>{const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet([{Transaksi:report.totals.transactions,Pendapatan:report.totals.revenue}]),'Ringkasan');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(report.trend),'Tren Harian');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(report.topProducts),'Produk Terlaris');XLSX.writeFile(book,'laporan-penjualan.xlsx')}
const exportReportPdf=(report:Report)=>{const pdf=new jsPDF({unit:'mm',format:'a4'});pdf.setFontSize(16);pdf.text('Laporan Penjualan',14,16);pdf.setFontSize(10);pdf.text(`Transaksi: ${report.totals.transactions}`,14,27);pdf.text(`Pendapatan: ${money(report.totals.revenue)}`,14,34);pdf.text('Tren Harian',14,46);report.trend.slice(0,26).forEach((item,index)=>pdf.text(`${item.date}  ${item.transactions} transaksi  ${money(item.revenue)}`,14,54+index*7));pdf.save('laporan-penjualan.pdf')}
const nav:[string,IconName,Role[]][]=[['Dashboard','grid',['admin','kasir']],['Produk','bag',['admin']],['Kategori','tag',['admin']],['Transaksi','receipt',['admin','kasir']],['Laporan','chart',['admin']],['Pelanggan','users',['admin']],['Pengaturan','settings',['admin']]]
const LS_CART='kk_cart', LS_CUSTOMER='kk_customer', LS_DISCOUNT='kk_discount', LS_DTYPE='kk_dtype', LS_OFFLINE_CHECKOUTS='kk_offline_checkouts'
function lsGet<T>(key:string,fallback:T):T{try{const v=localStorage.getItem(key);return v!==null?JSON.parse(v) as T:fallback}catch{return fallback}}
function lsSet<T>(key:string,value:T){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function lsDel(...keys:string[]){keys.forEach(k=>{try{localStorage.removeItem(k)}catch{}})}

function App(){
 const [user,setUser]=useState<User|null>(null),[booting,setBooting]=useState(true),[active,setActive]=useState('Dashboard')
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[transactions,setTransactions]=useState<Transaction[]>([])
 const [customers,setCustomers]=useState<Customer[]>([]),[settings,setSettings]=useState<Settings>({storeName:'KasirKita',taxRate:11})
 const [dashboard,setDashboard]=useState<DashboardData>({sales:0,transactions:0,stock:0,customers:0}),[report,setReport]=useState<Report|null>(null)
 const [shift,setShift]=useState<Shift|null>(null)
 const [cart,setCart]=useState<Record<number,number>>(()=>lsGet(LS_CART,{}))
 const [customerName,setCustomerName]=useState<string>(()=>lsGet(LS_CUSTOMER,'Pelanggan Umum'))
 const [discount,setDiscount]=useState<number>(()=>lsGet(LS_DISCOUNT,0))
 const [discountType,setDiscountType]=useState<DiscountType>(()=>lsGet(LS_DTYPE,'nominal'))
 useEffect(()=>{lsSet(LS_CART,cart)},[cart])
 useEffect(()=>{lsSet(LS_CUSTOMER,customerName)},[customerName])
 useEffect(()=>{lsSet(LS_DISCOUNT,discount)},[discount])
 useEffect(()=>{lsSet(LS_DTYPE,discountType)},[discountType])
 const [search,setSearch]=useState(''),[category,setCategory]=useState('Semua')
 const [stockFilter,setStockFilter]=useState<StockFilter>('semua'),[showDashFilter,setShowDashFilter]=useState(false)
 const [sidebar,setSidebar]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[payment,setPayment]=useState<Payment>('Tunai'),[cash,setCash]=useState(0)
 const [checkoutOpen,setCheckoutOpen]=useState(false),[receipt,setReceipt]=useState<Transaction|null>(null)
 const [toast,setToast]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const [productForm,setProductForm]=useState<Product|null>(null),[customerForm,setCustomerForm]=useState(false),[categoryName,setCategoryName]=useState('')
 const [cancelModal,setCancelModal]=useState<Transaction|null>(null)
 const [openShiftModal,setOpenShiftModal]=useState(false),[closeShiftModal,setCloseShiftModal]=useState(false)
 const [shiftSummary,setShiftSummary]=useState<{openingCash:number;shiftRevenue:number;expectedCash:number;closingCash:number;difference:number}|null>(null)
 const [txFrom,setTxFrom]=useState(''),[txTo,setTxTo]=useState(''),[reportCashierId,setReportCashierId]=useState('')
 const notify=(msg:string)=>{setToast(msg);window.setTimeout(()=>setToast(''),2400)}
 const requestError=(e:unknown)=>{const m=e instanceof Error?e.message:'Terjadi kesalahan.';setError(m);window.setTimeout(()=>setError(''),4500)}
 const load=async(u:User)=>{
  try{
   const [p,c,s,d,t]=await Promise.all([api<{products:Product[]}>('/products'),api<{categories:Category[]}>('/categories'),api<{settings:Settings}>('/settings'),api<{dashboard:DashboardData}>('/dashboard'),api<{transactions:Transaction[]}>('/transactions')])
   setProducts(p.products);setCategories(c.categories);setSettings(s.settings);setDashboard(d.dashboard);setTransactions(t.transactions)
   if(u.role==='admin'){const [cd,rd]=await Promise.all([api<{customers:Customer[]}>('/customers'),api<{report:Report}>('/reports')]);setCustomers(cd.customers);setReport(rd.report)}
   if(u.role==='kasir'){const {shift:sh}=await api<{shift:Shift|null}>('/shifts/active');setShift(sh)}
  }catch(e){requestError(e)}
 }
   const syncOfflineCheckouts=async(u:User)=>{if(!navigator.onLine)return;const queue=lsGet<OfflineCheckout[]>(LS_OFFLINE_CHECKOUTS,[]);if(!queue.length)return;const remaining:OfflineCheckout[]=[];for(const item of queue){try{await api('/checkout',{method:'POST',body:JSON.stringify(item.payload)})}catch{remaining.push(item)}}lsSet(LS_OFFLINE_CHECKOUTS,remaining);if(remaining.length<queue.length){await load(u);notify(`${queue.length-remaining.length} transaksi offline tersinkronisasi`)}}
   useEffect(()=>{api<{user:User}>('/auth/me').then(async({user})=>{setUser(user);await load(user);await syncOfflineCheckouts(user)}).catch(()=>setUser(null)).finally(()=>setBooting(false))},[])
   useEffect(()=>{const sync=()=>{if(user)void syncOfflineCheckouts(user)};window.addEventListener('online',sync);return()=>window.removeEventListener('online',sync)},[user])
 const filtered=useMemo(()=>products.filter(p=>{
  const mC=category==='Semua'||p.category===category
  const mS=`${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase())
  const mSt=stockFilter==='semua'||(stockFilter==='tersedia'&&p.stock>0&&p.stock>=10)||(stockFilter==='rendah'&&p.stock>0&&p.stock<10)||(stockFilter==='habis'&&p.stock===0)
  return mC&&mS&&mSt
 }),[products,category,search,stockFilter])
 const cartProducts=products.filter(p=>cart[p.id])
 const subtotal=cartProducts.reduce((s,p)=>s+p.price*cart[p.id],0)
 const appliedDiscount=discountType==='persen'?Math.round(subtotal*(Math.min(Math.max(discount||0,0),100)/100)):Math.min(Math.max(discount||0,0),subtotal)
 const previewTax=Math.round((subtotal-appliedDiscount)*settings.taxRate/100)
 const previewTotal=subtotal-appliedDiscount+previewTax
 const updateCart=(id:number,delta:number)=>{const p=products.find(x=>x.id===id);if(!p)return;setCart(cur=>{const next=Math.max(0,Math.min(p.stock,(cur[id]||0)+delta));if(!next){const{[id]:_,...rest}=cur;return rest}return{...cur,[id]:next}})}
 const add=(p:Product)=>{if(!p.stock)return notify('Stok produk habis');if(user?.role==='kasir'&&!shift)return notify('Buka kasir terlebih dahulu sebelum transaksi.');updateCart(p.id,1)}
 const login=async(u:string,pw:string)=>{setSaving(true);try{const d=await api<{user:User}>('/auth/login',{method:'POST',body:JSON.stringify({username:u,password:pw})});setUser(d.user);await load(d.user);notify(`Selamat datang, ${d.user.displayName}`)}catch(e){requestError(e)}finally{setSaving(false)}}
 const logout=async()=>{try{await api('/auth/logout',{method:'POST'});setUser(null);setProducts([]);setCart({})}catch(e){requestError(e)}}
 const clearCart=()=>{setCart({});setDiscount(0);setCustomerName('Pelanggan Umum');setDiscountType('nominal');lsDel(LS_CART,LS_CUSTOMER,LS_DISCOUNT,LS_DTYPE);notify('Keranjang dikosongkan')}
 useEffect(()=>{const handleCartMenu=(event:MouseEvent)=>{if((event.target as HTMLElement).closest('.dots-button'))clearCart()};document.addEventListener('click',handleCartMenu);return()=>document.removeEventListener('click',handleCartMenu)},[])
 const refresh=async()=>{if(user)await load(user)}
 const pollPayment=async(transaction:Transaction)=>{if(!transaction.databaseId)return;let attempts=0;const check=async():Promise<void>=>{attempts+=1;try{const d=await api<{payment:{status:TransactionStatus;paymentStatus:string;cancelReason:string|null}}>(`/transactions/${transaction.databaseId}/payment`);if(d.payment.status==='completed'){await refresh();setReceipt({...transaction,status:'completed',paymentStatus:d.payment.paymentStatus});notify('Pembayaran dikonfirmasi Midtrans')}else if(d.payment.status==='cancelled'){await refresh();setReceipt({...transaction,status:'cancelled',paymentStatus:d.payment.paymentStatus,cancelReason:d.payment.cancelReason});requestError(new Error('Pembayaran tidak berhasil. Stok telah dikembalikan.'))}else if(attempts<30){window.setTimeout(()=>{void check()},2000)}else notify('Pembayaran masih menunggu konfirmasi gateway. Cek riwayat transaksi.')}catch(e){requestError(e)}};await check()}
 const openMidtrans=async(transaction:Transaction)=>{if(!transaction.snapToken||!transaction.clientKey)return;try{let script=document.getElementById('midtrans-snap-script') as HTMLScriptElement|null;if(!script){script=document.createElement('script');script.id='midtrans-snap-script';script.src='https://app.sandbox.midtrans.com/snap/snap.js';script.setAttribute('data-client-key',transaction.clientKey);document.body.appendChild(script);await new Promise<void>((resolve,reject)=>{script!.addEventListener('load',()=>resolve(),{once:true});script!.addEventListener('error',()=>reject(new Error('Snap.js gagal dimuat.')),{once:true})})}if(!window.snap)throw new Error('Midtrans Snap belum siap.');window.snap.pay(transaction.snapToken,{onSuccess:()=>{notify('Pembayaran diterima, menunggu webhook Midtrans...');void pollPayment(transaction)},onPending:()=>{notify('Pembayaran menunggu konfirmasi Midtrans...');void pollPayment(transaction)},onError:()=>requestError(new Error('Midtrans menolak pembayaran.')),onClose:()=>notify('Jendela pembayaran ditutup. Status tetap menunggu konfirmasi.')})}catch(e){requestError(e)}}
 const checkout=async()=>{
  if(!cartProducts.length)return
  if(user?.role==='kasir'&&!shift)return requestError(new Error('Buka kasir terlebih dahulu.'))
  const payload={items:cartProducts.map(p=>({id:p.id,quantity:cart[p.id]})),discount:appliedDiscount,payment,cashReceived:cash,customerName}
  setSaving(true);try{
   const d=await api<{transaction:Transaction}>('/checkout',{method:'POST',body:JSON.stringify(payload)})
    setCheckoutOpen(false);setCart({});setDiscount(0);setCash(0)
   lsDel(LS_CART,LS_CUSTOMER,LS_DISCOUNT,LS_DTYPE);setCustomerName('Pelanggan Umum');setDiscountType('nominal')
    await refresh();if(d.transaction.status==='pending'){notify('Transaksi dibuat. Selesaikan pembayaran di Midtrans.');await openMidtrans(d.transaction)}else{setReceipt(d.transaction);notify('Transaksi berhasil disimpan')}
  }catch(e){if(payment==='Tunai'&&(!navigator.onLine||e instanceof TypeError)){const queue=lsGet<OfflineCheckout[]>(LS_OFFLINE_CHECKOUTS,[]);queue.push({id:crypto.randomUUID(),payload,createdAt:new Date().toISOString()});lsSet(LS_OFFLINE_CHECKOUTS,queue);setCheckoutOpen(false);setCart({});notify('Koneksi terputus. Transaksi Tunai disimpan dan akan disinkronkan saat online.')}else requestError(e)}finally{setSaving(false)}
 }
 const cancelTransaction=async(trx:Transaction,reason:string)=>{if(!trx.databaseId)return;setSaving(true);try{await api(`/transactions/${trx.databaseId}/cancel`,{method:'POST',body:JSON.stringify({reason})});setCancelModal(null);await refresh();notify('Transaksi berhasil dibatalkan')}catch(e){requestError(e)}finally{setSaving(false)}}
 const openShift=async(oc:number)=>{setSaving(true);try{const {shift:s}=await api<{shift:Shift}>('/shifts/open',{method:'POST',body:JSON.stringify({openingCash:oc})});setShift(s);setOpenShiftModal(false);notify(`Kasir dibuka. Kas awal: ${money(oc)}`)}catch(e){requestError(e)}finally{setSaving(false)}}
 const closeShift=async(cc:number,notes:string)=>{setSaving(true);try{const {summary}=await api<{summary:{openingCash:number;shiftRevenue:number;expectedCash:number;closingCash:number;difference:number}}>('/shifts/close',{method:'POST',body:JSON.stringify({closingCash:cc,notes})});setShift(null);setCloseShiftModal(false);setShiftSummary(summary)}catch(e){requestError(e)}finally{setSaving(false)}}
 const loadTransactions=async(from:string,to:string)=>{try{const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);const d=await api<{transactions:Transaction[]}>(`/transactions${p.toString()?`?${p.toString()}`:''}`);setTransactions(d.transactions)}catch(e){requestError(e)}}
 const loadReports=async(from:string,to:string,cashierId=reportCashierId)=>{if(user?.role!=='admin')return;try{const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);if(cashierId)p.set('cashierId',cashierId);const d=await api<{report:Report}>(`/reports${p.toString()?`?${p.toString()}`:''}`);setReport(d.report);setReportCashierId(cashierId)}catch(e){requestError(e)}}
 const saveProduct=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{let image=String(f.get('image')||'');const imageFile=f.get('imageFile');if(imageFile instanceof File&&imageFile.size){const uploadData=new FormData();uploadData.append('image',imageFile);const uploaded=await api<{image:string}>('/uploads/product-image',{method:'POST',body:uploadData});image=uploaded.image}const body={name:String(f.get('name')),sku:String(f.get('sku')),category:String(f.get('category')),price:Number(f.get('price')),stock:Number(f.get('stock')),image};await api(productForm?.id?`/products/${productForm.id}`:'/products',{method:productForm?.id?'PUT':'POST',body:JSON.stringify(body)});setProductForm(null);await refresh();notify('Produk berhasil disimpan')}catch(e){requestError(e)}finally{setSaving(false)}}
 const removeProduct=async(id:number)=>{if(!confirm('Hapus produk ini?'))return;try{await api(`/products/${id}`,{method:'DELETE'});await refresh();notify('Produk dihapus')}catch(e){requestError(e)}}
 const addCategory=async()=>{const name=categoryName.trim();if(!name)return notify('Nama kategori wajib diisi.');setSaving(true);try{await api('/categories',{method:'POST',body:JSON.stringify({name})});setCategoryName('');await refresh();notify('Kategori ditambahkan')}catch(e){requestError(e)}finally{setSaving(false)}}
 const removeCategory=async(id:number)=>{try{await api(`/categories/${id}`,{method:'DELETE'});await refresh();notify('Kategori dihapus')}catch(e){requestError(e)}}
 const saveSettings=async(e:FormEvent)=>{e.preventDefault();try{const r=await api<{settings:Settings}>('/settings',{method:'PUT',body:JSON.stringify(settings)});setSettings(r.settings);notify('Pengaturan berhasil disimpan')}catch(e){requestError(e)}}
 const addCustomer=async(name:string,phone:string)=>{try{await api('/customers',{method:'POST',body:JSON.stringify({name,phone})});setCustomerForm(false);await refresh();notify('Pelanggan ditambahkan')}catch(e){requestError(e)}}
 if(booting)return <div className="app-loading"><div className="brand-mark">K</div><p>Menyiapkan KasirKita…</p></div>
 if(!user)return <Login onLogin={login} busy={saving} error={error}/>
 const permitted=nav.filter(([,,roles])=>roles.includes(user.role))
 const labels:Record<string,[string,string]>={Dashboard:['Kasir yang lebih ringkas.','Kelola pesanan dan pantau penjualan hari ini.'],Produk:['Katalog produk','Atur barang, harga, kategori, dan stok Anda.'],Kategori:['Kategori produk','Susun katalog yang mudah ditemukan kasir.'],Transaksi:['Riwayat transaksi','Pembayaran Anda tercatat aman di server.'],Laporan:['Ringkasan penjualan','Data penjualan berdasarkan transaksi tersimpan.'],Pelanggan:['Data pelanggan','Kenali pelanggan yang kembali berbelanja.'],Pengaturan:['Pengaturan toko','Hanya pemilik yang dapat mengubah aturan toko.']}
 const heading=labels[active];const shiftBlocked=user.role==='kasir'&&!shift
 const notificationMessages=[...(user.role==='kasir'&&shiftBlocked?['Shift kasir belum dibuka.']:[]),...(transactions.some(t=>t.status==='pending')?['Ada pembayaran yang masih menunggu konfirmasi.']:[]),...(user.role==='admin'&&products.some(p=>p.stock<10)?['Ada produk dengan stok rendah.']:[])]
 return <div className="app-shell">
  <aside className={`sidebar ${sidebar?'is-open':''}`}>
   <div className="brand"><span className="brand-mark">K</span><span>KasirKita</span></div>
   <div className="store-switcher"><div className="store-avatar">K</div><div><strong>{settings.storeName}</strong><small>{user.role==='admin'?'Pemilik toko':'Kasir'}</small></div><Icon name="chevron" size={16}/></div>
   <nav>{permitted.slice(0,5).map(([label,icon])=><button className={active===label?'nav-link active':'nav-link'} key={label} onClick={()=>{setActive(label);setSidebar(false)}}><Icon name={icon}/><span>{label}</span>{label==='Transaksi'&&transactions.length>0&&<em>{transactions.length}</em>}</button>)}</nav>
   <div className="nav-bottom">
    <nav>{permitted.slice(5).map(([label,icon])=><button className={active===label?'nav-link active':'nav-link'} key={label} onClick={()=>{setActive(label);setSidebar(false)}}><Icon name={icon}/><span>{label}</span></button>)}</nav>
    {user.role==='kasir'&&(shift?<button className="shift-button shift-close" onClick={()=>setCloseShiftModal(true)}><Icon name="shift" size={17}/>Tutup Kasir</button>:<button className="shift-button shift-open" onClick={()=>setOpenShiftModal(true)}><Icon name="shift" size={17}/>Buka Kasir</button>)}
    <button className="logout-link" onClick={logout}><Icon name="logout" size={17}/> Keluar</button>
    <div className="profile"><div className="avatar">{user.displayName.slice(0,2).toUpperCase()}</div><div><strong>{user.displayName}</strong><small>{user.role==='admin'?'Admin / Owner':shift?'Shift aktif':'Kasir (belum buka)'}</small></div></div>
   </div>
  </aside>
  {sidebar&&<button className="backdrop" onClick={()=>setSidebar(false)}/>}
  <main className="main-content">
   <header className="topbar">
    <button className="mobile-menu" onClick={()=>setSidebar(true)}><Icon name="menu"/></button>
    <div className="breadcrumbs"><span>{settings.storeName}</span><Icon name="chevron" size={14}/><strong>{active}</strong></div>
    <div className="top-actions"><div className="notification-wrap"><button className={`notification${notificationsOpen?' active':''}`} onClick={()=>setNotificationsOpen(open=>!open)} aria-label="Lihat notifikasi"><Icon name="bell" size={19}/>{notificationMessages.length>0&&<i/>}</button>{notificationsOpen&&<div className="notification-panel"><div className="notification-heading"><strong>Notifikasi</strong><button onClick={()=>setNotificationsOpen(false)} aria-label="Tutup notifikasi"><Icon name="close" size={14}/></button></div>{notificationMessages.length?notificationMessages.map(message=><div className="notification-item" key={message}><span>!</span><p>{message}</p></div>):<p className="notification-empty">Tidak ada notifikasi baru.</p>}</div>}</div><div className="top-avatar">{user.displayName.slice(0,2).toUpperCase()}</div></div>
   </header>
   <section className="page-heading">
    <div><p className="eyebrow">{user.role==='admin'?'PANEL PEMILIK':'SESI KASIR'}</p><h1>{heading[0]}</h1><p className="intro">{heading[1]}</p></div>
    <div className="date-button"><Icon name="calendar" size={17}/><span>{new Intl.DateTimeFormat('id-ID',{dateStyle:'long'}).format(new Date())}</span></div>
   </section>
   {shiftBlocked&&active==='Dashboard'&&<div className="shift-banner"><div><Icon name="shift" size={22}/><div><strong>Kasir belum dibuka</strong><p>Buka kasir terlebih dahulu untuk mulai transaksi hari ini.</p></div></div><button className="primary-button" onClick={()=>setOpenShiftModal(true)}>Buka Kasir <Icon name="arrow" size={17}/></button></div>}
  {active==='Dashboard'&&<Dashboard products={products} filtered={filtered} categories={categories.map(c=>c.name)} category={category} setCategory={setCategory} stockFilter={stockFilter} setStockFilter={setStockFilter} showDashFilter={showDashFilter} setShowDashFilter={setShowDashFilter} search={search} setSearch={setSearch} add={add} cartProducts={cartProducts} cart={cart} updateCart={updateCart} clearCart={clearCart} subtotal={subtotal} discount={discount} setDiscount={setDiscount} discountType={discountType} setDiscountType={setDiscountType} appliedDiscount={appliedDiscount} tax={previewTax} taxRate={settings.taxRate} total={previewTotal} customerName={customerName} setCustomerName={setCustomerName} openCheckout={()=>setCheckoutOpen(true)} stats={dashboard} shiftBlocked={shiftBlocked}/>} 
   {active==='Produk'&&<Products products={filtered} categories={categories.map(c=>c.name)} search={search} setSearch={setSearch} category={category} setCategory={setCategory} onAdd={()=>setProductForm({id:0,name:'',sku:'',category:categories[0]?.name||'',price:0,stock:0,image:''})} onEdit={setProductForm} onDelete={removeProduct}/>}
  {active==='Kategori'&&<Categories categories={categories} name={categoryName} setName={setCategoryName} add={addCategory} remove={removeCategory} busy={saving}/>} 
  {active==='Transaksi'&&<Transactions transactions={transactions} show={setReceipt} onCancel={setCancelModal} userRole={user.role} from={txFrom} setFrom={setTxFrom} to={txTo} setTo={setTxTo} onFilter={()=>loadTransactions(txFrom,txTo)} onReset={()=>{setTxFrom('');setTxTo('');loadTransactions('','')}}/>}
  {active==='Laporan'&&<Reports report={report} onFilter={loadReports}/>} 
   {active==='Pelanggan'&&<Customers customers={customers} add={()=>setCustomerForm(true)}/>}
   {active==='Pengaturan'&&<SettingsPage settings={settings} setSettings={setSettings} save={saveSettings}/>}
  </main>
  {checkoutOpen&&<Checkout total={previewTotal} payment={payment} setPayment={setPayment} cash={cash} setCash={setCash} close={()=>setCheckoutOpen(false)} pay={checkout} busy={saving}/>}
  {receipt&&<Receipt transaction={receipt} store={settings.storeName} close={()=>setReceipt(null)}/>}
  {productForm&&<ProductModal product={productForm} categories={categories.map(c=>c.name)} close={()=>setProductForm(null)} save={saveProduct} busy={saving}/>}
  {customerForm&&<CustomerModal close={()=>setCustomerForm(false)} save={addCustomer} busy={saving}/>}
  {cancelModal&&<CancelModal transaction={cancelModal} close={()=>setCancelModal(null)} confirm={cancelTransaction} busy={saving}/>}
  {openShiftModal&&<OpenShiftModal close={()=>setOpenShiftModal(false)} confirm={openShift} busy={saving}/>}
  {closeShiftModal&&shift&&<CloseShiftModal shift={shift} close={()=>setCloseShiftModal(false)} confirm={closeShift} busy={saving}/>}
  {shiftSummary&&<ShiftSummaryModal summary={shiftSummary} close={()=>setShiftSummary(null)}/>}
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  {error&&<div className="error-toast">{error}</div>}
 </div>
}
function Login({onLogin,busy,error}:{onLogin:(u:string,p:string)=>void;busy:boolean;error:string}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);onLogin(String(d.get('username')),String(d.get('password')))};return <main className="login-page"><div className="login-panel"><div className="brand"><span className="brand-mark">K</span><span>KasirKita</span></div><div className="login-intro"><p className="eyebrow">SISTEM KASIR AMAN</p><h1>Masuk ke toko Anda</h1><p>Gunakan akun yang diberikan pemilik toko.</p></div><form onSubmit={submit}><label>Username<input name="username" autoComplete="username" autoFocus required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button login-button" disabled={busy}>{busy?'Memeriksa akun…':'Masuk'} <Icon name="arrow" size={17}/></button></form></div></main>}
function Metric({icon,tone,label,value,note}:{icon:IconName;tone:string;label:string;value:string;note:string}){return <article className="metric-card"><div className={`metric-icon ${tone}`}><Icon name={icon} size={20}/></div><div><p>{label}</p><div className="metric-value"><h2>{value}</h2></div><small>{note}</small></div></article>}
type Dash={products:Product[];filtered:Product[];categories:string[];category:string;setCategory:(s:string)=>void;stockFilter:StockFilter;setStockFilter:(s:StockFilter)=>void;showDashFilter:boolean;setShowDashFilter:(b:boolean)=>void;search:string;setSearch:(s:string)=>void;add:(p:Product)=>void;cartProducts:Product[];cart:Record<number,number>;updateCart:(id:number,d:number)=>void;clearCart:()=>void;subtotal:number;discount:number;setDiscount:(n:number)=>void;discountType:DiscountType;setDiscountType:(t:DiscountType)=>void;appliedDiscount:number;tax:number;taxRate:number;total:number;customerName:string;setCustomerName:(s:string)=>void;openCheckout:()=>void;stats:DashboardData;shiftBlocked:boolean}
function Dashboard(p:Dash){return <><section className="metrics"><Metric icon="chart" tone="amber" label="Penjualan hari ini" value={money(p.stats.sales)} note="Berdasarkan server"/><Metric icon="receipt" tone="lavender" label="Transaksi" value={String(p.stats.transactions)} note="Pembayaran berhasil"/><Metric icon="box" tone="blue" label="Total stok" value={String(p.stats.stock)} note="Unit tersedia"/><Metric icon="users" tone="coral" label="Pelanggan" value={String(p.stats.customers)} note="Pelanggan terdaftar"/></section><section className="workspace"><div className="catalog-panel"><div className="section-heading"><div><h2>Penjualan cepat</h2><p>Harga dan stok final selalu divalidasi server.</p></div></div><div className="catalog-controls"><div className="search-field"><Icon name="search" size={18}/><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="Cari nama atau SKU..."/></div><button className={`filter-button${p.showDashFilter?' active':''}`} onClick={()=>p.setShowDashFilter(!p.showDashFilter)}><Icon name="filter" size={18}/><span>Filter</span></button></div>{p.showDashFilter&&<div className="dash-filter-panel"><div><p className="filter-label">Stok</p><div className="filter-chips">{(['semua','tersedia','rendah','habis'] as StockFilter[]).map(v=><button key={v} className={`chip${p.stockFilter===v?' selected':''}`} onClick={()=>p.setStockFilter(v)}>{v==='semua'?'Semua':v==='tersedia'?'Tersedia':v==='rendah'?'Stok rendah':'Habis'}</button>)}</div></div></div>}<div className="category-tabs">{['Semua',...p.categories].map(c=><button key={c} className={p.category===c?'selected':''} onClick={()=>p.setCategory(c)}>{c}</button>)}</div><div className="product-grid">{p.filtered.map(x=><article className={`product-card${!x.stock?' sold-out':''}`} key={x.id}><div className="product-image"><img src={x.image||'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80'} alt={x.name}/><span className={x.stock<10?'low-stock':''}>{x.stock?`${x.stock} stok`:'Habis'}</span></div><div className="product-info"><div><p className="product-category">{x.category}</p><h3>{x.name}</h3><strong>{money(x.price)}</strong></div><button onClick={()=>p.add(x)} disabled={!x.stock}><Icon name="plus" size={18}/></button></div></article>)}{!p.filtered.length&&<Empty title="Produk belum tersedia" text="Owner dapat menambah produk dari menu Produk."/>}</div></div><Cart {...p}/></section></>}
function Cart(p:Dash){return <aside className="cart-panel"><div className="cart-head"><div><h2>Pesanan aktif</h2><p>{p.cartProducts.length} jenis produk</p></div><button className="dots-button"><Icon name="dots"/></button></div><div className="customer-field"><Icon name="users" size={16}/><input value={p.customerName} onChange={e=>p.setCustomerName(e.target.value)} placeholder="Nama pelanggan"/></div><div className="cart-items">{p.cartProducts.length?p.cartProducts.map(x=><div className="cart-item" key={x.id}><img src={x.image||'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80'} alt=""/><div className="cart-item-info"><h3>{x.name}</h3><p>{money(x.price)}</p><div className="quantity"><button onClick={()=>p.updateCart(x.id,-1)}><Icon name="minus" size={13}/></button><span>{p.cart[x.id]}</span><button onClick={()=>p.updateCart(x.id,1)} disabled={p.cart[x.id]>=x.stock}><Icon name="plus" size={13}/></button></div></div><strong>{money(x.price*p.cart[x.id])}</strong><button className="delete" onClick={()=>p.updateCart(x.id,-p.cart[x.id])}><Icon name="trash" size={17}/></button></div>):<Empty title="Pesanan masih kosong" text="Tambahkan produk dari katalog." icon="bag"/>}</div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(p.subtotal)}</strong></div><div className="discount-row"><label>Diskon</label><div className="discount-input-group"><input type="number" min="0" max={p.discountType==='persen'?100:undefined} value={p.discount||''} onChange={e=>p.setDiscount(Number(e.target.value))} placeholder="0"/><button className={`discount-type-btn${p.discountType==='persen'?' active':''}`} onClick={()=>p.setDiscountType(p.discountType==='persen'?'nominal':'persen')} title={p.discountType==='persen'?'Ganti ke nominal (Rp)':'Ganti ke persen (%)'}>{p.discountType==='persen'?<Icon name="percent" size={14}/>:'Rp'}</button></div>{p.appliedDiscount>0&&<small className="discount-preview">= -{money(p.appliedDiscount)}</small>}</div><div><span>Pajak <small>({p.taxRate}%)</small></span><strong>{money(p.tax)}</strong></div><div className="total"><span>Total</span><strong>{money(p.total)}</strong></div><button className="checkout-button" onClick={p.openCheckout} disabled={!p.cartProducts.length||p.shiftBlocked}><span>{p.shiftBlocked?'Buka kasir dulu':'Lanjut pembayaran'}</span><Icon name="arrow" size={18}/></button></div></aside>}
function Products({products,categories,search,setSearch,category,setCategory,onAdd,onEdit,onDelete}:{products:Product[];categories:string[];search:string;setSearch:(s:string)=>void;category:string;setCategory:(s:string)=>void;onAdd:()=>void;onEdit:(p:Product)=>void;onDelete:(id:number)=>void}){return <section className="content-card"><div className="content-toolbar"><div className="search-field"><Icon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama atau SKU..."/></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="Semua">Semua kategori</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="primary-button" onClick={onAdd}><Icon name="plus" size={17}/> Tambah produk</button></div><div className="data-table product-table"><div className="table-head"><span>Produk</span><span>Kategori</span><span>Harga</span><span>Stok</span><span/></div>{products.map(p=><div className="table-row" key={p.id}><div className="table-product"><img src={p.image||'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80'} alt=""/><div><strong>{p.name}</strong><small>{p.sku}</small></div></div><span><b className="badge">{p.category}</b></span><strong>{money(p.price)}</strong><span className={p.stock<10?'stock-low':''}>{p.stock} unit</span><div className="row-actions"><button onClick={()=>onEdit(p)}><Icon name="edit" size={16}/></button><button onClick={()=>onDelete(p.id)}><Icon name="trash" size={16}/></button></div></div>)}{!products.length&&<Empty title="Belum ada produk" text="Tambahkan produk pertama Anda."/>}</div></section>}
function Categories({categories,name,setName,add,remove,busy}:{categories:Category[];name:string;setName:(s:string)=>void;add:()=>void;remove:(id:number)=>void;busy:boolean}){return <section className="content-card"><form className="content-toolbar" onSubmit={e=>{e.preventDefault();add()}}><div className="field-inline"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama kategori baru" autoComplete="off"/><button className="primary-button" type="submit" disabled={busy}><Icon name="plus" size={17}/> {busy?'Menyimpan…':'Tambah kategori'}</button></div></form><div className="category-manager">{categories.map((c,i)=><article className="category-card" key={c.id}><div className={`category-blob blob-${i%4}`}><Icon name="tag" size={20}/></div><div><h3>{c.name}</h3><p>{c.productCount} produk</p></div><button onClick={()=>remove(c.id)}><Icon name="trash" size={17}/></button></article>)}</div></section>}
function Transactions({transactions,show,onCancel,userRole,from,setFrom,to,setTo,onFilter,onReset}:{transactions:Transaction[];show:(t:Transaction)=>void;onCancel:(t:Transaction)=>void;userRole:Role;from:string;setFrom:(s:string)=>void;to:string;setTo:(s:string)=>void;onFilter:()=>void;onReset:()=>void}){
 const today=todayISO()
 const canCancel=(t:Transaction)=>{if(t.status==='cancelled')return false;if(userRole==='admin')return true;return t.date.slice(0,10)===today}
 return <section className="content-card"><div className="table-intro"><div><h2>Riwayat transaksi</h2><p>{transactions.length} transaksi tersedia untuk akun ini</p></div><div className="report-actions"><button className="text-button" onClick={()=>exportTransactionsXlsx(transactions)}>Excel</button><button className="text-button" onClick={()=>exportTransactionsPdf(transactions)}>PDF</button></div></div><div className="tx-filter-bar"><div className="tx-date-range"><Icon name="calendar" size={16}/><label>Dari <input type="date" value={from} onChange={e=>setFrom(e.target.value)} max={to||today}/></label><label>Sampai <input type="date" value={to} onChange={e=>setTo(e.target.value)} min={from} max={today}/></label></div><div className="tx-filter-actions"><button className="primary-button" onClick={onFilter}><Icon name="filter" size={16}/> Tampilkan</button><button className="text-button" onClick={onReset}><Icon name="refresh" size={16}/> Reset</button></div></div><div className="data-table transaction-table"><div className="table-head"><span>Nomor &amp; waktu</span><span>Pelanggan</span><span>Metode</span><span>Total</span><span>Status</span><span/></div>{transactions.map(t=><div className={`table-row${t.status==='cancelled'?' row-cancelled':''}`} key={t.id}><div><strong>{t.id}</strong><small>{dateText(t.date)}</small></div><span>{t.customer}</span><span><b className="badge payment-badge">{t.payment}</b></span><strong>{money(t.total)}</strong><span>{t.status==='cancelled'?<b className="badge badge-cancelled">Dibatalkan</b>:<b className="badge badge-completed">Selesai</b>}</span><div className="row-actions"><button className="receipt-action" onClick={()=>show(t)}><Icon name="receipt" size={16}/> Struk</button>{canCancel(t)&&<button className="cancel-action" onClick={()=>onCancel(t)}><Icon name="ban" size={16}/> Batal</button>}</div></div>)}{!transactions.length&&<Empty title="Belum ada transaksi" text="Transaksi selesai akan muncul di sini." icon="receipt"/>}</div></section>
}
function Reports({report,onFilter}:{report:Report|null;onFilter:(from:string,to:string,cashierId?:string)=>void}){
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [cashierId,setCashierId]=useState('');const today=todayISO();const trend=report?.trend||[];const maxRevenue=Math.max(...trend.map(x=>x.revenue),1)
 return <div className="report-grid"><section className="content-card report-filter-bar"><div className="tx-filter-bar"><div className="tx-date-range"><Icon name="calendar" size={16}/><label>Dari <input type="date" value={from} onChange={e=>setFrom(e.target.value)} max={to||today}/></label><label>Sampai <input type="date" value={to} onChange={e=>setTo(e.target.value)} min={from} max={today}/></label><select value={cashierId} onChange={e=>setCashierId(e.target.value)}><option value="">Semua kasir</option>{(report?.cashiers||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="tx-filter-actions"><button className="primary-button" onClick={()=>onFilter(from,to,cashierId)}><Icon name="filter" size={16}/> Tampilkan</button><button className="text-button" onClick={()=>{setFrom('');setTo('');setCashierId('');onFilter('','','')}}><Icon name="refresh" size={16}/> Reset</button></div></div><div className="report-actions"><button className="text-button" disabled={!report} onClick={()=>report&&exportReportXlsx(report)}>Excel</button><button className="text-button" disabled={!report} onClick={()=>report&&exportReportPdf(report)}>PDF</button></div></section><section className="content-card report-summary"><Metric icon="chart" tone="amber" label="Total pendapatan" value={money(report?.totals.revenue||0)} note="Dari seluruh transaksi"/><Metric icon="receipt" tone="lavender" label="Transaksi" value={String(report?.totals.transactions||0)} note="Pembayaran berhasil"/><Metric icon="bag" tone="blue" label="Rata-rata transaksi" value={money(report?.totals.transactions?(report.totals.revenue/report.totals.transactions):0)} note="Nilai per pembayaran"/></section><section className="content-card trend-card"><div className="table-intro"><div><h2>Tren penjualan</h2><p>Pendapatan harian pada rentang yang dipilih.</p></div></div><div className="trend-bars">{trend.length?trend.map(item=><div className="trend-column" key={item.date} title={`${item.date}: ${money(item.revenue)}`}><div className="trend-bar" style={{height:`${Math.max(8,item.revenue/maxRevenue*150)}px`}}/><small>{item.date.slice(5)}</small></div>):<Empty title="Belum ada tren" text="Pilih rentang tanggal dengan transaksi." icon="chart"/>}</div></section><Rank title="Produk terlaris" description="Diurutkan dari jumlah produk terjual." rows={(report?.topProducts||[]).map((x,i)=><div key={x.name}><span>{i+1}</span><strong>{x.name}</strong><b>{x.quantity} terjual</b></div>)} empty="Belum ada data penjualan"/><Rank title="Stok perlu diperhatikan" description="Produk dengan stok di bawah 10 unit." rows={(report?.lowStock||[]).map(x=><div key={x.id}><span className="warning">!</span><strong>{x.name}</strong><b>{x.stock} tersisa</b></div>)} empty="Stok dalam kondisi baik"/></div>
}
function Rank({title,description,rows,empty}:{title:string;description:string;rows:ReactNode[];empty:string}){return <section className="content-card"><div className="table-intro"><div><h2>{title}</h2><p>{description}</p></div></div><div className="rank-list">{rows.length?rows:<Empty title={empty} text="Data akan tampil setelah ada aktivitas." icon="chart"/>}</div></section>}
function Customers({customers,add}:{customers:Customer[];add:()=>void}){return <section className="content-card"><div className="content-toolbar"><div><h2>Daftar pelanggan</h2><p>Riwayat diperbarui oleh server setelah checkout.</p></div><button className="primary-button" onClick={add}><Icon name="userplus" size={17}/> Tambah pelanggan</button></div><div className="data-table customers-table"><div className="table-head"><span>Pelanggan</span><span>Kontak</span><span>Kunjungan</span><span>Total belanja</span></div>{customers.map(c=><div className="table-row" key={c.id}><div className="customer-name"><i>{c.name.slice(0,1).toUpperCase()}</i><strong>{c.name}</strong></div><span>{c.phone||'—'}</span><span>{c.visits} kali</span><strong>{money(c.spend)}</strong></div>)}{!customers.length&&<Empty title="Belum ada pelanggan" text="Tambahkan pelanggan atau isi nama di pesanan aktif." icon="users"/>}</div></section>}
function SettingsPage({settings,setSettings,save}:{settings:Settings;setSettings:(s:Settings)=>void;save:(e:FormEvent)=>void}){return <section className="settings-card content-card"><form onSubmit={save}><div className="settings-section"><h2>Identitas toko</h2><label>Nama toko<input value={settings.storeName} onChange={e=>setSettings({...settings,storeName:e.target.value})}/></label><p className="hint">Nama kasir berasal dari akun yang sedang login, bukan dari pengaturan toko.</p></div><div className="settings-section"><h2>Aturan transaksi</h2><label>Tarif pajak (%)<input type="number" min="0" max="100" value={settings.taxRate} onChange={e=>setSettings({...settings,taxRate:Number(e.target.value)})}/></label><p className="hint">Server menghitung pajak dan total akhir saat checkout.</p></div><button className="primary-button" type="submit"><Icon name="check" size={17}/> Simpan pengaturan</button></form></section>}
function Empty({title,text,icon='search'}:{title:string;text:string;icon?:IconName}){return <div className="empty"><div><Icon name={icon} size={23}/></div><h3>{title}</h3><p>{text}</p></div>}
function Checkout({total,payment,setPayment,cash,setCash,close,pay,busy}:{total:number;payment:Payment;setPayment:(p:Payment)=>void;cash:number;setCash:(n:number)=>void;close:()=>void;pay:()=>void;busy:boolean}){const change=Math.max(0,cash-total);return <div className="modal-wrap"><div className="pay-modal"><button className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">PEMBAYARAN</p><h2>{money(total)}</h2><p className="modal-copy">Server akan memvalidasi ulang harga dan stok sebelum menyimpan pembayaran.</p><div className="payment-methods">{(['Tunai','QRIS','Debit / Kredit','E-Wallet'] as Payment[]).map(n=><button key={n} className={payment===n?'selected':''} onClick={()=>setPayment(n)}><Icon name={n==='Tunai'?'cash':'wallet'} size={19}/><span>{n}</span>{payment===n&&<Icon name="check" size={16}/>}</button>)}</div>{payment==='Tunai'&&<div className="cash-input"><label>Uang diterima<input autoFocus type="number" min="0" value={cash||''} onChange={e=>setCash(Number(e.target.value))} placeholder="0"/></label><div><span>Kembalian</span><strong>{money(change)}</strong></div></div>}{payment==='QRIS'&&<div className="qris-box"><div className="qr-pattern">▦</div><p>Simulasi pembayaran QRIS</p></div>}<button className="checkout-button pay-button" onClick={pay} disabled={busy}><span>{busy?'Memproses…':'Konfirmasi pembayaran'}</span><Icon name="arrow" size={18}/></button></div></div>}
function Receipt({transaction,store,close}:{transaction:Transaction;store:string;close:()=>void}){
 const isCancelled=transaction.status==='cancelled'
 const print=()=>{const rows=transaction.items.map(i=>`<tr><td>${i.name} × ${i.quantity}</td><td style="text-align:right">${money(i.price*i.quantity)}</td></tr>`).join('');const win=window.open('','_blank','width=320,height=680');if(!win)return;win.document.write(`<html><head><title>${transaction.id}</title><style>@page{size:58mm auto;margin:0}*{box-sizing:border-box}body{width:58mm;margin:0;padding:4mm 3mm;font-family:monospace;font-size:10px;line-height:1.35;color:#111}h1,p{text-align:center;margin:2px 0}h1{font-size:14px}hr{border:0;border-top:1px dashed #111;margin:8px 0}table{width:100%;border-collapse:collapse;margin:8px 0}td{padding:2px 0;vertical-align:top}.total{font-weight:bold;font-size:12px}.cancelled{color:#b00;font-weight:bold;text-align:center}@media print{body{width:58mm}}</style></head><body><h1>${store}</h1><p>Struk Pembayaran</p><hr>No. ${transaction.id}<br>${dateText(transaction.date)}<br>Kasir: ${transaction.cashier}<br>Pelanggan: ${transaction.customer}${isCancelled?`<p class="cancelled">TRANSAKSI DIBATALKAN<br>${transaction.cancelReason||''}</p>`:''}<table>${rows}</table><table><tr><td>Subtotal</td><td style="text-align:right">${money(transaction.subtotal)}</td></tr><tr><td>Diskon</td><td style="text-align:right">-${money(transaction.discount)}</td></tr><tr><td>Pajak</td><td style="text-align:right">${money(transaction.tax)}</td></tr><tr class="total"><td>Total</td><td style="text-align:right">${money(transaction.total)}</td></tr></table><hr><p>Terima kasih</p><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}
 return <div className="modal-wrap"><div className="receipt-modal"><button className="modal-close" onClick={close}><Icon name="close"/></button><div className={`receipt-success${isCancelled?' receipt-cancelled':''}`}><Icon name={isCancelled?'ban':'check'} size={25}/></div><p className="eyebrow">{isCancelled?'TRANSAKSI DIBATALKAN':'TRANSAKSI BERHASIL'}</p><h2>{isCancelled?'Transaksi ini dibatalkan':'Pembayaran diterima'}</h2><p className="modal-copy">{transaction.id} · {dateText(transaction.date)}</p>{isCancelled&&transaction.cancelReason&&<p className="modal-copy" style={{color:'#e53e3e',fontStyle:'italic'}}>Alasan: {transaction.cancelReason}</p>}<div className="receipt-lines">{transaction.items.map(i=><div key={i.id}><span>{i.name} × {i.quantity}</span><strong>{money(i.price*i.quantity)}</strong></div>)}<hr/><div><span>Subtotal</span><strong>{money(transaction.subtotal)}</strong></div>{transaction.discount>0&&<div><span>Diskon</span><strong>-{money(transaction.discount)}</strong></div>}<div><span>Pajak</span><strong>{money(transaction.tax)}</strong></div><div className="receipt-total"><span>Total</span><strong>{money(transaction.total)}</strong></div><div><span>{transaction.payment}</span><strong>{money(transaction.cashReceived)}</strong></div>{transaction.payment==='Tunai'&&<div><span>Kembalian</span><strong>{money(transaction.change)}</strong></div>}</div><button className="primary-button receipt-print" onClick={print}><Icon name="printer" size={17}/> Cetak / Simpan PDF</button><button className="text-button" onClick={close}>Tutup</button></div></div>
}
function CancelModal({transaction,close,confirm,busy}:{transaction:Transaction;close:()=>void;confirm:(t:Transaction,reason:string)=>void;busy:boolean}){const [reason,setReason]=useState('');return <div className="modal-wrap"><div className="form-modal small-form"><button type="button" className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">PEMBATALAN TRANSAKSI</p><h2>Batalkan {transaction.id}?</h2><p className="modal-copy">Stok produk akan dikembalikan otomatis. Tindakan ini tidak dapat dibatalkan.</p><div className="form-grid one-col"><label>Alasan pembatalan <span style={{color:'#e53e3e'}}>*</span><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tulis alasan pembatalan..." rows={3}/></label></div><button className="danger-button full-button" disabled={busy||!reason.trim()} onClick={()=>confirm(transaction,reason)}><Icon name="ban" size={17}/> {busy?'Membatalkan…':'Konfirmasi Pembatalan'}</button><button className="text-button" onClick={close}>Kembali</button></div></div>}
function OpenShiftModal({close,confirm,busy}:{close:()=>void;confirm:(cash:number)=>void;busy:boolean}){const [cash,setCash]=useState(0);return <div className="modal-wrap"><div className="form-modal small-form"><button type="button" className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">BUKA KASIR</p><h2>Mulai shift hari ini</h2><p className="modal-copy">Masukkan jumlah uang tunai yang ada di laci kasir sebelum mulai transaksi.</p><div className="form-grid one-col"><label>Kas awal (Rp)<input type="number" min="0" value={cash||''} onChange={e=>setCash(Number(e.target.value))} placeholder="0" autoFocus/></label></div><button className="primary-button full-button" disabled={busy} onClick={()=>confirm(cash)}><Icon name="shift" size={17}/> {busy?'Membuka…':'Buka Kasir'}</button></div></div>}
function CloseShiftModal({shift,close,confirm,busy}:{shift:Shift;close:()=>void;confirm:(cash:number,notes:string)=>void;busy:boolean}){const [cash,setCash]=useState(0);const [notes,setNotes]=useState('');return <div className="modal-wrap"><div className="form-modal small-form"><button type="button" className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">TUTUP KASIR</p><h2>Akhiri shift</h2><p className="modal-copy">Shift dibuka: {dateText(shift.openedAt)} · Kas awal: {money(shift.openingCash)}</p><div className="form-grid one-col"><label>Kas fisik saat ini (Rp)<input type="number" min="0" value={cash||''} onChange={e=>setCash(Number(e.target.value))} placeholder="0" autoFocus/></label><label>Catatan (opsional)<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Catatan penutup shift..."/></label></div><button className="primary-button full-button" disabled={busy} onClick={()=>confirm(cash,notes)}><Icon name="check" size={17}/> {busy?'Menutup…':'Tutup Kasir & Lihat Laporan'}</button></div></div>}
function ShiftSummaryModal({summary,close}:{summary:{openingCash:number;shiftRevenue:number;expectedCash:number;closingCash:number;difference:number};close:()=>void}){const diff=summary.difference;const isShort=diff<0;const isOver=diff>0;return <div className="modal-wrap"><div className="receipt-modal"><button className="modal-close" onClick={close}><Icon name="close"/></button><div className={`receipt-success${isShort?' receipt-cancelled':''}`}><Icon name={isShort?'ban':isOver?'bell':'check'} size={25}/></div><p className="eyebrow">LAPORAN TUTUP KASIR</p><h2>{isShort?'Ada selisih kurang':isOver?'Ada selisih lebih':'Kas sesuai!'}</h2><div className="receipt-lines"><div><span>Kas awal</span><strong>{money(summary.openingCash)}</strong></div><div><span>Pendapatan shift</span><strong>+{money(summary.shiftRevenue)}</strong></div><div className="receipt-total"><span>Kas seharusnya</span><strong>{money(summary.expectedCash)}</strong></div><hr/><div><span>Kas fisik (input)</span><strong>{money(summary.closingCash)}</strong></div><div className="receipt-total"><span style={{fontWeight:'bold'}}>Selisih</span><strong style={{color:isShort?'#e53e3e':isOver?'#d69e2e':'inherit'}}>{diff>=0?'+':''}{money(diff)}</strong></div></div><button className="primary-button receipt-print" onClick={close}><Icon name="check" size={17}/> Selesai</button></div></div>}
function ProductModal({product,categories,close,save,busy}:{product:Product;categories:string[];close:()=>void;save:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <div className="modal-wrap"><form className="form-modal" onSubmit={save}><button type="button" className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">{product.id?'EDIT PRODUK':'PRODUK BARU'}</p><h2>{product.id?'Perbarui produk':'Tambahkan produk'}</h2><div className="form-grid"><label>Nama produk<input name="name" defaultValue={product.name} required/></label><label>SKU<input name="sku" defaultValue={product.sku} required/></label><label>Kategori<select name="category" defaultValue={product.category} required>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Harga (Rp)<input name="price" type="number" min="0" defaultValue={product.price} required/></label><label>Stok<input name="stock" type="number" min="0" defaultValue={product.stock} required/></label><label>Gambar produk<input name="imageFile" type="file" accept="image/*"/></label></div>{product.image&&<p className="hint">Gambar saat ini akan dipertahankan jika tidak memilih file baru.</p>}<button className="primary-button full-button" disabled={busy} type="submit"><Icon name="check" size={17}/> {busy?'Menyimpan…':'Simpan produk'}</button></form></div>}
function CustomerModal({close,save,busy}:{close:()=>void;save:(name:string,phone:string)=>void;busy:boolean}){return <div className="modal-wrap"><form className="form-modal small-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);save(String(d.get('name')),String(d.get('phone')))}}><button type="button" className="modal-close" onClick={close}><Icon name="close"/></button><p className="eyebrow">PELANGGAN BARU</p><h2>Tambah pelanggan</h2><div className="form-grid one-col"><label>Nama pelanggan<input name="name" required autoFocus/></label><label>Nomor telepon<input name="phone" type="tel"/></label></div><button className="primary-button full-button" disabled={busy}><Icon name="check" size={17}/> Simpan pelanggan</button></form></div>}
createRoot(document.getElementById('root')!).render(<App />)
